import type { Career, CareerRankItem } from '@/types/career'
import type { DimensionScores } from '@/types/diagnosis'

export const CAREERS: Career[] = [
  // IT系
  {
    id: 'software-engineer',
    slug: 'software-engineer',
    name: 'ソフトウェアエンジニア',
    category: 'it',
    description: 'プログラミングとシステム設計で価値あるプロダクトを構築する',
    medianIncome: 720,
    incomeRange: { min: 400, max: 2000 },
    requiredSkills: ['プログラミング', 'システム設計', 'アルゴリズム', '問題解決力'],
    avgYearsToReach: 3,
    growthOutlook: 'growing',
    workStyle: ['リモート可', '成果主義', 'チーム開発'],
    careerPath: ['ジュニアエンジニア', 'シニアエンジニア', 'テックリード', 'CTO'],
    relatedCareers: ['data-scientist', 'product-manager', 'devops-engineer'],
  },
  {
    id: 'data-scientist',
    slug: 'data-scientist',
    name: 'データサイエンティスト',
    category: 'it',
    description: 'データ分析とAI/MLで意思決定を科学的にサポートする',
    medianIncome: 800,
    incomeRange: { min: 500, max: 2500 },
    requiredSkills: ['統計学', 'Python/R', '機械学習', 'ビジネス理解', 'SQL'],
    avgYearsToReach: 4,
    growthOutlook: 'growing',
    workStyle: ['リモート可', 'データドリブン', '研究的'],
    careerPath: ['アナリスト', 'データサイエンティスト', 'MLエンジニア', 'AIリサーチャー'],
    relatedCareers: ['software-engineer', 'consultant', 'quantitative-analyst'],
  },
  {
    id: 'product-manager',
    slug: 'product-manager',
    name: 'プロダクトマネージャー',
    category: 'it',
    description: 'ユーザーとビジネスの橋渡しをしながら製品戦略を立案・実行する',
    medianIncome: 900,
    incomeRange: { min: 600, max: 2500 },
    requiredSkills: ['プロダクト戦略', 'データ分析', 'UX思考', 'コミュニケーション', 'ロードマップ設計'],
    avgYearsToReach: 5,
    growthOutlook: 'growing',
    workStyle: ['クロスファンクショナル', '意思決定多い', '結果責任'],
    careerPath: ['APM', 'PM', 'シニアPM', 'VP of Product', 'CPO'],
    relatedCareers: ['software-engineer', 'ux-designer', 'startup-founder'],
  },
  // ビジネス系
  {
    id: 'management-consultant',
    slug: 'management-consultant',
    name: '経営コンサルタント',
    category: 'business',
    description: '高度な分析と知識で企業の戦略課題を解決するアドバイザー',
    medianIncome: 1200,
    incomeRange: { min: 700, max: 3000 },
    requiredSkills: ['戦略思考', '問題解決力', 'コミュニケーション', '業界知識', 'プレゼン'],
    avgYearsToReach: 5,
    growthOutlook: 'stable',
    workStyle: ['高強度', '出張多い', 'プロジェクト単位'],
    careerPath: ['アナリスト', 'コンサルタント', 'マネージャー', 'パートナー'],
    relatedCareers: ['cfo', 'startup-founder', 'venture-capitalist'],
  },
  {
    id: 'startup-founder',
    slug: 'startup-founder',
    name: 'スタートアップ創業者',
    category: 'entrepreneurship',
    description: 'ゼロから事業を立ち上げ、市場に新たな価値を創出する',
    medianIncome: 2000,
    incomeRange: { min: 0, max: 100000 },
    requiredSkills: ['事業構築力', 'リーダーシップ', '資金調達', '市場調査', '採用力'],
    avgYearsToReach: 7,
    growthOutlook: 'growing',
    workStyle: ['高リスク高リターン', '全権限', '激務'],
    careerPath: ['副業・スモールビジネス', 'シードスタートアップ', 'シリーズA以降', 'EXIT'],
    relatedCareers: ['product-manager', 'venture-capitalist', 'management-consultant'],
  },
  {
    id: 'marketing-director',
    slug: 'marketing-director',
    name: 'マーケティングディレクター',
    category: 'business',
    description: '市場戦略を設計し、ブランドと顧客をつなぐマーケティングを統括する',
    medianIncome: 800,
    incomeRange: { min: 500, max: 2000 },
    requiredSkills: ['マーケティング戦略', 'データ分析', 'ブランディング', 'デジタルマーケ', 'コピーライティング'],
    avgYearsToReach: 8,
    growthOutlook: 'growing',
    workStyle: ['クリエイティブ', 'データドリブン', '多様なステークホルダー'],
    careerPath: ['マーケター', 'マーケティングマネージャー', 'CMO'],
    relatedCareers: ['product-manager', 'ux-designer', 'startup-founder'],
  },
  // 金融系
  {
    id: 'venture-capitalist',
    slug: 'venture-capitalist',
    name: 'ベンチャーキャピタリスト',
    category: 'finance',
    description: 'スタートアップを発掘・投資し、次世代の産業を育てる',
    medianIncome: 1500,
    incomeRange: { min: 800, max: 10000 },
    requiredSkills: ['投資分析', 'スタートアップ理解', 'ネットワーク', '財務モデリング', '事業評価'],
    avgYearsToReach: 10,
    growthOutlook: 'growing',
    workStyle: ['高裁量', '投資判断', 'ネットワーク重要'],
    careerPath: ['アナリスト', 'アソシエイト', 'VP', 'パートナー', 'GP'],
    relatedCareers: ['management-consultant', 'startup-founder', 'investment-banker'],
  },
  {
    id: 'investment-banker',
    slug: 'investment-banker',
    name: '投資銀行家',
    category: 'finance',
    description: 'M&A・IPO・資金調達などの大型金融取引をアドバイザリングする',
    medianIncome: 1300,
    incomeRange: { min: 700, max: 5000 },
    requiredSkills: ['財務モデリング', 'M&A知識', 'プレゼン', '英語', '数的処理'],
    avgYearsToReach: 6,
    growthOutlook: 'stable',
    workStyle: ['超高強度', '高報酬', 'エリート環境'],
    careerPath: ['アナリスト', 'アソシエイト', 'VP', 'ディレクター', 'MD'],
    relatedCareers: ['venture-capitalist', 'management-consultant', 'private-equity'],
  },
  // クリエイティブ系
  {
    id: 'ux-designer',
    slug: 'ux-designer',
    name: 'UX/UIデザイナー',
    category: 'creative',
    description: 'ユーザーの体験を設計し、使いやすく美しいプロダクトを創る',
    medianIncome: 600,
    incomeRange: { min: 350, max: 1500 },
    requiredSkills: ['UI設計', 'ユーザーリサーチ', 'Figma', 'プロトタイピング', 'デザインシステム'],
    avgYearsToReach: 3,
    growthOutlook: 'growing',
    workStyle: ['クリエイティブ', 'コラボレーション', 'ツール重要'],
    careerPath: ['UIデザイナー', 'UXデザイナー', 'デザインリード', 'CDO'],
    relatedCareers: ['product-manager', 'software-engineer', 'brand-designer'],
  },
  {
    id: 'content-creator',
    slug: 'content-creator',
    name: 'コンテンツクリエイター',
    category: 'creative',
    description: '独自のコンテンツで多くの人を惹きつけ、メディアビジネスを構築する',
    medianIncome: 400,
    incomeRange: { min: 0, max: 10000 },
    requiredSkills: ['コンテンツ企画', '動画・文章制作', 'SNS運用', 'ブランディング', 'マネタイズ'],
    avgYearsToReach: 3,
    growthOutlook: 'growing',
    workStyle: ['自由度高い', '実力主義', '継続力必要'],
    careerPath: ['副業クリエイター', 'フルタイムクリエイター', 'メディア企業', '起業'],
    relatedCareers: ['marketing-director', 'startup-founder', 'ux-designer'],
  },
  // 医療・福祉系
  {
    id: 'physician',
    slug: 'physician',
    name: '医師',
    category: 'medical',
    description: '医学的知識と技術で患者の健康を守る社会的に重要な専門職',
    medianIncome: 1400,
    incomeRange: { min: 1000, max: 5000 },
    requiredSkills: ['医学知識', '診断力', 'コミュニケーション', '体力・精神力', '判断力'],
    avgYearsToReach: 12,
    growthOutlook: 'stable',
    workStyle: ['責任重大', '専門性重視', '継続学習必須'],
    careerPath: ['研修医', '専攻医', '専門医', '部長・院長', '教授'],
    relatedCareers: ['nurse-practitioner', 'medical-researcher', 'healthcare-consultant'],
  },
  // 法律・士業系
  {
    id: 'lawyer',
    slug: 'lawyer',
    name: '弁護士・司法書士・行政書士',
    category: 'legal',
    description: '法律の知識と論理で人々の権利と正義を守るプロフェッショナル',
    medianIncome: 1000,
    incomeRange: { min: 500, max: 5000 },
    requiredSkills: ['法律知識', '論理的思考', '文書作成', '交渉力', '倫理観'],
    avgYearsToReach: 8,
    growthOutlook: 'stable',
    workStyle: ['専門性重視', '独立開業可', '責任重大'],
    careerPath: ['法学部・法科大学院', '司法試験合格', '弁護士・士業事務所', '独立開業'],
    relatedCareers: ['management-consultant', 'researcher'],
  },
  {
    id: 'project-manager',
    slug: 'project-manager',
    name: 'プロジェクトマネージャー',
    category: 'business',
    description: '計画・調整・実行を通じてチームを成功へ導くコーディネーター',
    medianIncome: 850,
    incomeRange: { min: 500, max: 2000 },
    requiredSkills: ['プロジェクト管理', 'リスク管理', 'チームマネジメント', 'コミュニケーション', 'スケジュール管理'],
    avgYearsToReach: 5,
    growthOutlook: 'growing',
    workStyle: ['調整役', '多部門連携', '成果責任'],
    careerPath: ['担当者', 'リーダー', 'プロジェクトマネージャー', 'PMO', 'CxO'],
    relatedCareers: ['software-engineer', 'management-consultant', 'product-manager'],
  },
  {
    id: 'web-designer',
    slug: 'web-designer',
    name: 'Webデザイナー',
    category: 'creative',
    description: '美的センスと技術でユーザーが使いたくなるデジタル体験を作るデザイナー',
    medianIncome: 550,
    incomeRange: { min: 300, max: 1500 },
    requiredSkills: ['UI/UXデザイン', 'Figma・Adobe XD', 'HTML/CSS', 'ブランディング', 'コーディング基礎'],
    avgYearsToReach: 3,
    growthOutlook: 'growing',
    workStyle: ['リモート可', 'フリーランス多い', 'クリエイティブ'],
    careerPath: ['デザイナー', 'シニアデザイナー', 'デザインリード', 'CDO'],
    relatedCareers: ['ux-designer', 'content-creator', 'marketing-director'],
  },
  {
    id: 'hr-specialist',
    slug: 'hr-specialist',
    name: '人事・HRスペシャリスト',
    category: 'business',
    description: '人と組織をつなぎ、働きやすい環境と優秀な人材を育てるピープルマネージャー',
    medianIncome: 600,
    incomeRange: { min: 400, max: 1500 },
    requiredSkills: ['採用・面接', '労務管理', '組織開発', 'コーチング', '法令知識'],
    avgYearsToReach: 4,
    growthOutlook: 'growing',
    workStyle: ['対人業務多い', '戦略的役割', 'チームワーク重視'],
    careerPath: ['人事担当', '人事マネージャー', 'HRBPパートナー', 'CHO'],
    relatedCareers: ['management-consultant', 'educator'],
  },
  {
    id: 'nurse',
    slug: 'nurse',
    name: '看護師・保健師',
    category: 'medical',
    description: '高い共感力と技術力で患者・利用者に寄り添う医療・ケアのプロ',
    medianIncome: 600,
    incomeRange: { min: 450, max: 1200 },
    requiredSkills: ['看護技術', '医療知識', 'コミュニケーション', '観察力', 'チームワーク'],
    avgYearsToReach: 4,
    growthOutlook: 'stable',
    workStyle: ['シフト制', '専門性重視', '社会貢献'],
    careerPath: ['看護師', '認定看護師', '専門看護師', '看護師長', '看護部長'],
    relatedCareers: ['physician', 'counselor', 'researcher'],
  },
  {
    id: 'writer',
    slug: 'writer',
    name: 'ライター・編集者',
    category: 'creative',
    description: '言葉と表現力で読者に価値を届けるコンテンツクリエイター',
    medianIncome: 450,
    incomeRange: { min: 200, max: 1500 },
    requiredSkills: ['文章力', '取材・インタビュー', 'SEO知識', '企画力', '調査力'],
    avgYearsToReach: 3,
    growthOutlook: 'stable',
    workStyle: ['リモート可', 'フリーランス多い', '自律的'],
    careerPath: ['ライター', 'シニアライター', '編集者', '編集長', '独立'],
    relatedCareers: ['content-creator', 'marketing-director', 'researcher'],
  },
  {
    id: 'counselor',
    slug: 'counselor',
    name: 'カウンセラー・コーチ',
    category: 'welfare',
    description: '傾聴と共感で人々の心に寄り添い、成長を支援するサポーター',
    medianIncome: 450,
    incomeRange: { min: 300, max: 1200 },
    requiredSkills: ['傾聴力', '心理学の基礎', 'コーチングスキル', '共感力', '自己管理力'],
    avgYearsToReach: 4,
    growthOutlook: 'growing',
    workStyle: ['対人業務', '独立開業可', '継続学習必須'],
    careerPath: ['心理士・コーチ資格取得', 'カウンセラー', '独立開業', 'スーパーバイザー'],
    relatedCareers: ['educator', 'nurse', 'social-worker'],
  },
  {
    id: 'chef',
    slug: 'chef',
    name: '料理人・シェフ',
    category: 'craft',
    description: '創造性と技術で食という体験を通じて人を幸せにするアーティスト',
    medianIncome: 400,
    incomeRange: { min: 250, max: 2000 },
    requiredSkills: ['調理技術', '食材知識', '衛生管理', 'メニュー開発', '体力'],
    avgYearsToReach: 5,
    growthOutlook: 'stable',
    workStyle: ['現場仕事', '独立開業可', 'クリエイティブ'],
    careerPath: ['見習いコック', 'コック', 'シェフ', 'オーナーシェフ', 'プロデュース'],
    relatedCareers: ['content-creator', 'marketing-director'],
  },
  {
    id: 'beautician',
    slug: 'beautician',
    name: '美容師・スタイリスト',
    category: 'craft',
    description: '美と個性を引き出すセンスと技術で人々の自信を高めるスタイリスト',
    medianIncome: 350,
    incomeRange: { min: 250, max: 1200 },
    requiredSkills: ['カット・カラー技術', 'トレンド感覚', '接客力', '提案力', '体力'],
    avgYearsToReach: 3,
    growthOutlook: 'stable',
    workStyle: ['技術職', '独立開業可', '接客業'],
    careerPath: ['アシスタント', 'スタイリスト', 'トップスタイリスト', 'サロンオーナー'],
    relatedCareers: ['ux-designer', 'content-creator'],
  },
  {
    id: 'social-worker',
    slug: 'social-worker',
    name: '社会福祉士・NPOスタッフ',
    category: 'welfare',
    description: '社会課題に向き合い、人と地域のつながりをつくる変革者',
    medianIncome: 380,
    incomeRange: { min: 280, max: 700 },
    requiredSkills: ['福祉制度の知識', '相談援助', 'コミュニケーション', 'ネットワーク構築', '問題解決力'],
    avgYearsToReach: 4,
    growthOutlook: 'growing',
    workStyle: ['社会貢献', '多様な現場', 'チームワーク'],
    careerPath: ['福祉士', 'ケースワーカー', 'スーパーバイザー', '施設長・管理職'],
    relatedCareers: ['educator', 'counselor', 'nurse'],
  },
  // 教育・研究系
  {
    id: 'researcher',
    slug: 'researcher',
    name: '研究者・サイエンティスト',
    category: 'education',
    description: '知識の最前線を探求し、新たな発見をもたらすイノベーター',
    medianIncome: 750,
    incomeRange: { min: 400, max: 2000 },
    requiredSkills: ['研究設計', '統計・データ解析', '論文執筆', '専門知識', '英語'],
    avgYearsToReach: 8,
    growthOutlook: 'stable',
    workStyle: ['深い専門性', '自律的', '国際的'],
    careerPath: ['研究助手', 'ポスドク', '助教', '准教授', '教授'],
    relatedCareers: ['data-scientist', 'management-consultant', 'engineer'],
  },
]

export function rankCareersForUser(scores: DimensionScores): CareerRankItem[] {
  return CAREERS.map(career => {
    // Simple scoring based on career category alignment
    const aptitudeScore = calcAptitudeScore(career, scores)
    const successProbability = Math.round(aptitudeScore * 0.9)
    const incomeMultiplier = (
      scores.AM * 0.25 + scores.PE * 0.20 + scores.AT * 0.15 +
      scores.LP * 0.15 + scores.RT * 0.10 + scores.ID * 0.15
    ) / 100
    const estimatedMedianIncome = Math.round(career.medianIncome * (0.70 + incomeMultiplier * 0.60))

    return {
      career,
      aptitudeScore,
      successProbability: Math.min(95, successProbability),
      fitReason: getFitReason(career, scores),
      caution: getCaution(career, scores),
      estimatedMedianIncome,
    }
  }).sort((a, b) => b.aptitudeScore - a.aptitudeScore)
}

function calcAptitudeScore(career: Career, scores: DimensionScores): number {
  const categoryWeights: Record<string, Partial<Record<keyof DimensionScores, number>>> = {
    it:               { AT: 0.35, TA: 0.30, PE: 0.20, ID: 0.15 },
    business:         { AT: 0.25, LP: 0.25, AM: 0.25, SI: 0.25 },
    creative:         { CT: 0.35, ID: 0.30, PE: 0.20, SI: 0.15 },
    medical:          { AT: 0.30, PE: 0.30, SI: 0.25, TA: 0.15 },
    education:        { SI: 0.35, AT: 0.25, PE: 0.25, LP: 0.15 },
    finance:          { AT: 0.35, RT: 0.25, AM: 0.25, PE: 0.15 },
    public:           { SP: 0.35, SI: 0.30, PE: 0.25, AT: 0.10 },
    craft:            { TA: 0.35, PE: 0.35, SP: 0.20, AT: 0.10 },
    sales:            { SI: 0.40, AM: 0.30, RT: 0.20, LP: 0.10 },
    entrepreneurship: { RT: 0.25, AM: 0.25, ID: 0.25, LP: 0.25 },
    legal:            { AT: 0.40, PE: 0.30, LP: 0.20, SP: 0.10 },
    management:       { LP: 0.35, AT: 0.25, PE: 0.25, SI: 0.15 },
    design:           { CT: 0.40, TA: 0.30, ID: 0.20, PE: 0.10 },
    hr:               { SI: 0.35, LP: 0.30, AT: 0.20, PE: 0.15 },
    healthcare:       { SI: 0.35, TA: 0.30, PE: 0.25, AT: 0.10 },
    media:            { CT: 0.35, AT: 0.25, PE: 0.25, SI: 0.15 },
    wellness:         { SI: 0.45, PE: 0.25, AT: 0.20, LP: 0.10 },
    hospitality:      { CT: 0.30, TA: 0.30, PE: 0.25, SI: 0.15 },
    beauty:           { CT: 0.30, SI: 0.30, TA: 0.25, PE: 0.15 },
    welfare:          { SI: 0.40, PE: 0.25, LP: 0.20, AT: 0.15 },
  }

  const weights = categoryWeights[career.category] ?? { AM: 0.25, PE: 0.25, AT: 0.25, LP: 0.25 }
  let score = 0
  for (const [dim, weight] of Object.entries(weights)) {
    score += (scores[dim as keyof DimensionScores] ?? 0) * (weight as number)
  }
  return Math.round(Math.min(98, score))
}

function getFitReason(career: Career, scores: DimensionScores): string {
  const reasons: Record<string, string> = {
    it: scores.AT > 70 ? '高い分析思考力がシステム開発に直結します' : 'ロジカルな問題解決力を活かせます',
    business: scores.LP > 60 ? '優れたリーダーシップで組織を牽引できます' : '戦略思考とコミュニケーション力が強みです',
    creative: scores.CT > 60 ? '独自の発想力でオリジナリティの高い仕事ができます' : 'クリエイティブな感性を活かせます',
    medical: scores.SI > 70 ? '高い社会的知性で患者との信頼関係を築けます' : '専門的な知識と継続力を発揮できます',
    finance: scores.RT > 60 ? 'リスク耐性が金融の不確実な判断に向いています' : '分析力と数的推論が金融分野で活きます',
    entrepreneurship: scores.AM > 70 ? '高い達成動機が起業の原動力になります' : '革新的な発想とリスク耐性が起業に向いています',
  }
  return reasons[career.category] ?? 'あなたのスキルセットと高い親和性があります'
}

function getCaution(career: Career, scores: DimensionScores): string {
  const cautions: Record<string, string> = {
    it: scores.TA < 40 ? '技術スキルの継続的習得が必要です' : '技術の急速な変化への対応が求められます',
    business: scores.LP < 40 ? 'リーダーシップスキルの強化が必要です' : '高いストレス耐性が求められます',
    entrepreneurship: scores.PE < 50 ? '長期的な継続力の強化が必要です' : '初期の収入不安定期を乗り越える覚悟が必要です',
    medical: '非常に長い学習期間（6年以上）が必要です',
    finance: scores.AT < 60 ? '高度な数量的分析力が必要です' : '競争が激しく、継続的な自己研鑽が必要です',
  }
  return cautions[career.category] ?? '継続的なスキルアップが成功の鍵です'
}
