import type { Question } from '@/types/diagnosis'

export const QUESTIONS: Question[] = [
  // ─── Section A: 日常の選択シナリオ ────────────────────────────────
  {
    id: 1,
    section: 'A',
    sectionLabel: '日常の選択シナリオ',
    question: '転職のオファーが届きました。給与は30%アップですが、相手は設立2年のスタートアップです。どうしますか？',
    options: [
      { id: 'A', text: '不安はあるが、成長できるチャンスとして前向きに検討する', scores: { RT: 3, LP: 3, AM: 2, AT: 1 } },
      { id: 'B', text: 'まず副業として関わり、会社の実態を確認してから判断する', scores: { ID: 3, AM: 3, AT: 2, RT: 1 } },
      { id: 'C', text: 'リスクが高すぎる。現職の安定を優先する', scores: { SP: 2, AT: 2, PE: 2, LP: 1 } },
      { id: 'D', text: 'このオファーを材料に、現職で昇給交渉を試みる', scores: { AT: 3, RT: -1, AM: 2 } },
    ],
    measureTypes: ['RT', 'LP', 'AM', 'AT', 'ID'],
  },
  {
    id: 2,
    section: 'A',
    sectionLabel: '日常の選択シナリオ',
    question: '趣味で続けてきたハンドメイド販売に、大手の格安サービスが参入してきました。どうしますか？',
    options: [
      { id: 'A', text: '大手には真似できないこだわりをさらに磨き、プレミアム路線に集中する', scores: { AT: 3, ID: 2, AM: 2 } },
      { id: 'B', text: 'お客さんの声を集めて、独自の強みを打ち出す', scores: { ID: 3, AT: 2, SI: 2, AM: 2 } },
      { id: 'C', text: 'むしろ大手にコラボや卸の提案をしてみる', scores: { LP: 2, SI: 3, AM: 2, AT: 1 } },
      { id: 'D', text: 'ターゲットをさらに絞り、熱心なファンだけに特化する', scores: { AT: 3, ID: 2, SP: 1 } },
    ],
    measureTypes: ['AT', 'ID', 'SI', 'LP'],
  },
  {
    id: 3,
    section: 'A',
    sectionLabel: '日常の選択シナリオ',
    question: '2年間続けてきた習い事やスキル練習ですが、なかなか上達せず費用もかさんできました。どうしますか？',
    options: [
      { id: 'A', text: 'まだ諦めたくない。もう少しだけ続ける', scores: { PE: 2, AM: 2, RT: 2 } },
      { id: 'B', text: '一度立ち止まり、上達しない原因を徹底的に分析してから判断する', scores: { AT: 4, LP: 2, AM: 2 } },
      { id: 'C', text: '向いていないと認め、きっぱりやめる', scores: { LP: 3, AT: 2, SP: 1 } },
      { id: 'D', text: '全く別のアプローチで同じ目標を目指す方法を探す', scores: { ID: 3, RT: 2, AM: 3 } },
    ],
    measureTypes: ['AT', 'LP', 'PE', 'ID', 'RT'],
  },
  {
    id: 4,
    section: 'A',
    sectionLabel: '日常の選択シナリオ',
    question: 'フリマアプリで自作の商品を出品します。材料費は1,000円、同じような商品は2,000〜4,000円で売られています。いくらで出しますか？',
    options: [
      { id: 'A', text: '8,000〜10,000円。こだわりを伝えて高単価を狙う', scores: { RT: 2, ID: 2, AM: 3, AT: 1 } },
      { id: 'B', text: '3,000〜4,000円。相場に合わせる', scores: { SP: 2, AT: 2 } },
      { id: 'C', text: '1,500〜2,000円。まず売れることを優先する', scores: { RT: 2, AM: 2, LP: 1 } },
      { id: 'D', text: '最初は無料か格安で配り、口コミが広がってから値上げする', scores: { ID: 3, RT: 2, AM: 2, AT: 2 } },
    ],
    measureTypes: ['RT', 'ID', 'AM', 'AT'],
  },
  {
    id: 5,
    section: 'A',
    sectionLabel: '日常の選択シナリオ',
    question: 'グループ作業でリーダーを任されました。メンバーAはとても優秀だが自分勝手、メンバーBは実力は普通だがチームを盛り上げてくれます。どちらを重要な役割に配置しますか？',
    options: [
      { id: 'A', text: 'Aに任せる。実力が最優先だ', scores: { AT: 2, AM: 3, RT: 2 } },
      { id: 'B', text: 'Bに任せる。チームの雰囲気が成果を決める', scores: { SI: 3, LP: 2, SP: 1 } },
      { id: 'C', text: '役割をしっかり分けて、AとBどちらの強みも活かす', scores: { LP: 3, PE: 2, AT: 2 } },
      { id: 'D', text: 'AにはBがフォローに入る体制を作り、両方うまく機能させる', scores: { LP: 4, ID: 2, AT: 2 } },
    ],
    measureTypes: ['LP', 'AT', 'SI', 'AM'],
  },
  {
    id: 6,
    section: 'A',
    sectionLabel: '日常の選択シナリオ',
    question: '毎日の時間の使い方について、あなたの考えに一番近いのはどれですか？',
    options: [
      { id: 'A', text: '今やっていることより、新しいことにもっと時間を使いたい', scores: { ID: 4, RT: 3, AM: 3 } },
      { id: 'B', text: '今やっていることを磨きながら、少しずつ新しいことも試す', scores: { AT: 3, PE: 3, AM: 2 } },
      { id: 'C', text: '仲間や協力者と一緒に、新しい領域へ踏み出したい', scores: { AT: 3, RT: 2, LP: 2 } },
      { id: 'D', text: '今やっていることをより広い範囲に展開していきたい', scores: { LP: 3, AM: 3, AT: 2, RT: 2 } },
    ],
    measureTypes: ['ID', 'RT', 'AM', 'AT', 'LP'],
  },

  // ─── Section B: お金と時間の選択 ──────────────────────────────────
  {
    id: 7,
    section: 'B',
    sectionLabel: 'お金と時間の選択',
    question: '次の選択肢から、あなたが選ぶとしたらどれですか？',
    options: [
      { id: 'A', text: '確実に30万円もらえる', scores: { SP: 3, RT: -2 } },
      { id: 'B', text: '50%の確率で70万円、50%の確率で0円', scores: { RT: 3, AM: 2 } },
      { id: 'C', text: '確実に25万円 ＋ 25%の確率で追加20万円', scores: { AT: 3, SP: 1 } },
      { id: 'D', text: '20%の確率で150万円、80%の確率で0円', scores: { RT: 5, AM: 3, ID: 2 } },
    ],
    measureTypes: ['RT', 'SP', 'AM', 'AT'],
  },
  {
    id: 8,
    section: 'B',
    sectionLabel: 'お金と時間の選択',
    question: '次の選択肢なら、どれを選びますか？',
    options: [
      { id: 'A', text: '今すぐ10万円', scores: { SP: 3, RT: 1 } },
      { id: 'B', text: '1ヶ月後に12万円', scores: { AT: 2, PE: 2 } },
      { id: 'C', text: '6ヶ月後に20万円', scores: { PE: 4, AT: 2, AM: 2 } },
      { id: 'D', text: '3年後に100万円', scores: { PE: 5, AM: 3, AT: 3 } },
    ],
    measureTypes: ['PE', 'AM', 'AT', 'SP'],
  },
  {
    id: 9,
    section: 'B',
    sectionLabel: 'お金と時間の選択',
    question: '急に自由に使える100万円が手に入りました。どう使いますか？',
    options: [
      { id: 'A', text: 'すべて貯金・定期預金など安全な方法で保管する', scores: { SP: 5, RT: -3 } },
      { id: 'B', text: '半分を貯金、半分を投資信託で積み立てる', scores: { SP: 2, RT: 2, AT: 2 } },
      { id: 'C', text: '全額を株式や投資で積極的に運用する', scores: { RT: 3, AM: 3 } },
      { id: 'D', text: '自分のスキルアップや将来の事業に全額投資する', scores: { RT: 4, AM: 5, ID: 3, PE: 3 } },
    ],
    measureTypes: ['RT', 'SP', 'AM', 'ID'],
  },
  {
    id: 10,
    section: 'B',
    sectionLabel: 'お金と時間の選択',
    question: 'コインを10回投げて、すべて表が出ました。次の1回で表が出る確率はどのくらいだと思いますか？',
    options: [
      { id: 'A', text: 'かなり高い（表が出やすい流れになっている）', scores: { AT: -2 } },
      { id: 'B', text: '50%（コイン投げは毎回独立しているので変わらない）', scores: { AT: 5 } },
      { id: 'C', text: 'かなり低い（そろそろ裏が出るはずだ）', scores: { AT: -2 } },
      { id: 'D', text: '理論上は50%だが、なんとなく答えにくい', scores: { AT: 2 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 11,
    section: 'B',
    sectionLabel: 'お金と時間の選択',
    question: '2年前に20万円で買ったゲーム機やカメラが、最近ほとんど使っていません。売れば5万円になります。維持費（保管・保険等）は月2,000円かかります。どうしますか？',
    options: [
      { id: 'A', text: '20万円分使い倒すまで手放さない', scores: { AT: -2, SP: 2 } },
      { id: 'B', text: '今後の利用頻度とコストを計算して、合理的に判断する', scores: { AT: 5 } },
      { id: 'C', text: 'とりあえずもう少し様子を見る', scores: { SP: 1 } },
      { id: 'D', text: '5万円の売却で損した気がするので売りたくない', scores: { RT: -1, AT: -1 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 12,
    section: 'B',
    sectionLabel: 'お金と時間の選択',
    question: '「同年代の平均年収は約500万円」という記事を見た直後、あなたの3〜5年後の目標年収は？',
    options: [
      { id: 'A', text: '400〜600万円（平均前後でいい）', scores: { SP: 2, AM: 1 } },
      { id: 'B', text: '600〜900万円（平均より少し上を目指したい）', scores: { AM: 2, AT: 1 } },
      { id: 'C', text: '900〜1,500万円（しっかり稼ぎたい）', scores: { AM: 3, RT: 2, ID: 2 } },
      { id: 'D', text: '1,500万円以上（高収入を本気で目指す）', scores: { AM: 5, RT: 3, LP: 2 } },
    ],
    measureTypes: ['AM', 'RT', 'LP'],
  },

  // ─── Section C: あなたの考え方 ────────────────────────────────────
  {
    id: 13,
    section: 'C',
    sectionLabel: 'あなたの考え方',
    question: '「勉強した人は試験に合格する。田中さんは試験に合格した。では田中さんは勉強したか？」',
    options: [
      { id: 'A', text: 'はい、勉強したはずだ', scores: { AT: -2 } },
      { id: 'B', text: 'いいえ、勉強しなかったかもしれない', scores: { AT: -1 } },
      { id: 'C', text: '「勉強→合格」は「合格→勉強」を意味しないため、判断できない', scores: { AT: 5 } },
      { id: 'D', text: '合格したのだから、勉強した可能性が高い', scores: { AT: 1 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 14,
    section: 'C',
    sectionLabel: 'あなたの考え方',
    question: '「時計」という物を一言で言い換えるとしたら、最もしっくりくるのは？',
    options: [
      { id: 'A', text: '時間を知るための道具', scores: { AT: 0 } },
      { id: 'B', text: '人間が時間を管理・共有するために生まれたシステム', scores: { AT: 3, CT: 3 } },
      { id: 'C', text: '目に見えない時間を物理的に可視化したもの', scores: { AT: 4, CT: 4, ID: 2 } },
      { id: 'D', text: '有限な人間の命を刻み、意識させる装置', scores: { AT: 5, CT: 5, ID: 3 } },
    ],
    measureTypes: ['AT', 'CT', 'ID'],
  },
  {
    id: 15,
    section: 'C',
    sectionLabel: 'あなたの考え方',
    question: '友人が「最近なぜか毎月お金が足りなくなる」と相談してきました。あなたの最初のアドバイスは？',
    options: [
      { id: 'A', text: '無駄遣いをやめるよう伝える', scores: { AM: 1 } },
      { id: 'B', text: 'まず毎月の支出内訳を一緒に確認する', scores: { AT: 2 } },
      { id: 'C', text: '収入・固定費・変動費・貯蓄に分けて、どこで増減があるか整理する', scores: { AT: 5 } },
      { id: 'D', text: '節約できるサービスや方法を調べて教える', scores: { AT: 1 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 16,
    section: 'C',
    sectionLabel: 'あなたの考え方',
    question: '「東京都内のコンビニは何軒あるか？」と聞かれました。どう考えますか？',
    options: [
      { id: 'A', text: 'まったく見当もつかない', scores: { AT: 0 } },
      { id: 'B', text: 'なんとなく数千〜1万くらいかな（感覚で）', scores: { AT: 1 } },
      { id: 'C', text: '人口・生活圏の密度・競合数などから推定できる', scores: { AT: 4 } },
      { id: 'D', text: '人口÷来店頻度÷1店舗の処理数で論理的に計算できる', scores: { AT: 5 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 17,
    section: 'C',
    sectionLabel: 'あなたの考え方',
    question: '「月曜に1回、火曜に2回、水曜に4回、木曜に8回…」金曜は何回になりますか？',
    options: [
      { id: 'A', text: '9回', scores: { AT: 0 } },
      { id: 'B', text: '16回（2倍ずつ増えるパターン）', scores: { AT: 5 } },
      { id: 'C', text: '10回', scores: { AT: 0 } },
      { id: 'D', text: 'わからない', scores: { AT: 0 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 18,
    section: 'C',
    sectionLabel: 'あなたの考え方',
    question: '気に入った服が「20%OFF」セールで買えました。翌週さらに「20%OFF」になっていました。合計で元の価格の何%引きになっていますか？',
    options: [
      { id: 'A', text: '40%引き（20%＋20%で計算）', scores: { AT: -1 } },
      { id: 'B', text: '36%引き（0.8×0.8＝0.64、つまり64%の価格）', scores: { AT: 5 } },
      { id: 'C', text: '38%引き', scores: { AT: -1 } },
      { id: 'D', text: 'ちょっと複雑でわからない', scores: { AT: 0 } },
    ],
    measureTypes: ['AT'],
  },

  // ─── Section D: Big5 性格特性 ─────────────────────────────────────
  {
    id: 19,
    section: 'D',
    sectionLabel: '性格特性',
    question: '新しい経験・知識・挑戦に対して、最もあなたに当てはまるのは？',
    options: [
      { id: 'A', text: '新しい経験や知識を常に求め、未知の領域に飛び込むことが好き', scores: { ID: 3, CT: 3, RT: 2, AM: 2 } },
      { id: 'B', text: '慣れ親しんだ方法を好み、確実な道を選ぶ傾向がある', scores: { SP: 3, PE: 2 } },
      { id: 'C', text: '面白そうなものには挑戦するが、リスクは慎重に評価する', scores: { AT: 2, RT: 1, AM: 1 } },
      { id: 'D', text: '新しいアイデアを考えるのは好きだが、実行は慎重', scores: { CT: 3, ID: 2 } },
    ],
    measureTypes: ['ID', 'CT', 'SP', 'RT'],
  },
  {
    id: 20,
    section: 'D',
    sectionLabel: '性格特性',
    question: '締め切りや計画の管理について、最もあなたに当てはまるのは？',
    options: [
      { id: 'A', text: '綿密な計画を立て、着実に実行する。締め切りは必ず守る', scores: { PE: 4, SP: 2, AM: 2 } },
      { id: 'B', text: '大まかな方向性を決め、状況に応じて柔軟に対応する', scores: { AT: 2, ID: 2, AM: 2 } },
      { id: 'C', text: '直感的に動くことが多く、細かい計画は苦手', scores: { ID: 2, CT: 2 } },
      { id: 'D', text: '重要なことは守るが、細部にはこだわらない', scores: { AM: 2, LP: 1 } },
    ],
    measureTypes: ['PE', 'SP', 'ID', 'AM'],
  },
  {
    id: 21,
    section: 'D',
    sectionLabel: '性格特性',
    question: 'エネルギーを最も回復できる方法は？',
    options: [
      { id: 'A', text: '多くの人と話したり交流することでエネルギーが高まる', scores: { SI: 4, LP: 2 } },
      { id: 'B', text: '一人で静かに考えたり、好きなことをする時間でリフレッシュできる', scores: { AT: 3, CT: 2 } },
      { id: 'C', text: '少人数での深い会話が一番エネルギーになる', scores: { SI: 2, AT: 2 } },
      { id: 'D', text: 'チームで何かを作ったり達成することが活力になる', scores: { LP: 3, SI: 2, AM: 2 } },
    ],
    measureTypes: ['SI', 'LP', 'AT', 'CT'],
  },
  {
    id: 22,
    section: 'D',
    sectionLabel: '性格特性',
    question: 'グループや職場で意見が対立したとき、あなたはどうしますか？',
    options: [
      { id: 'A', text: '自分の意見をしっかり主張し、納得いくまで議論する', scores: { LP: 3, AM: 2 } },
      { id: 'B', text: '相手の立場を理解し、妥協点を積極的に探る', scores: { SI: 4, LP: 2 } },
      { id: 'C', text: '全体にとって最善を判断し、チームを方向づけるよう努める', scores: { LP: 4, AT: 3, SI: 2 } },
      { id: 'D', text: '対立は避け、周囲の意見に合わせることが多い', scores: { SP: 2, SI: 2 } },
    ],
    measureTypes: ['LP', 'SI', 'AT'],
  },
  {
    id: 23,
    section: 'D',
    sectionLabel: '性格特性',
    question: '締め切りや発表など、プレッシャーがかかる場面でのあなたは？',
    options: [
      { id: 'A', text: 'プレッシャーがあるほど燃えて、実力以上を発揮できる', scores: { AM: 3, LP: 2, RT: 2 } },
      { id: 'B', text: '多少緊張するが、通常通りのパフォーマンスが出る', scores: { PE: 3, SP: 2 } },
      { id: 'C', text: 'プレッシャーで集中力が増し、冷静かつ丁寧に対処できる', scores: { AT: 3, LP: 2, PE: 2 } },
      { id: 'D', text: '強いプレッシャーがかかるとパフォーマンスが落ちやすい', scores: { SP: 3 } },
    ],
    measureTypes: ['AM', 'LP', 'AT', 'PE'],
  },
  {
    id: 24,
    section: 'D',
    sectionLabel: '性格特性',
    question: '10年後の自分として、最もイメージに近い姿は？',
    options: [
      { id: 'A', text: '自分の会社やプロジェクトをリードし、大きな組織を動かしている', scores: { LP: 4, AM: 4, RT: 3, ID: 3 } },
      { id: 'B', text: 'ある分野で業界から認められる専門家になっている', scores: { PE: 4, AT: 3, TA: 3, AM: 3 } },
      { id: 'C', text: '安定した収入と充実したプライベートを両立して働いている', scores: { SP: 4, PE: 3 } },
      { id: 'D', text: '自分の仕事を通じて社会や業界に大きな変化をもたらしている', scores: { LP: 3, SI: 3, AM: 3, CT: 3 } },
    ],
    measureTypes: ['LP', 'AM', 'PE', 'SP', 'ID'],
  },

  // ─── Section E: 行動履歴・キャリア志向 ────────────────────────────
  {
    id: 25,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: '読書・学習・スキルアップに使う時間は週平均でどのくらいですか？',
    options: [
      { id: 'A', text: 'ほぼゼロ（1時間未満）', scores: { PE: 0, AM: 0 } },
      { id: 'B', text: '1〜3時間程度', scores: { PE: 1, AM: 1 } },
      { id: 'C', text: '3〜10時間程度', scores: { PE: 3, AM: 3, AT: 2 } },
      { id: 'D', text: '10時間以上', scores: { PE: 5, AM: 5, AT: 3, ID: 2 } },
    ],
    measureTypes: ['PE', 'AM', 'AT'],
  },
  {
    id: 26,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: '過去3年間で「少し怖い・難しい」と感じた挑戦をどれくらいしましたか？',
    options: [
      { id: 'A', text: 'ほぼしていない（1〜2回以下）', scores: { SP: 3, PE: 1 } },
      { id: 'B', text: '数回（3〜5回）', scores: { RT: 2, AM: 2, PE: 2 } },
      { id: 'C', text: '定期的に（6〜10回）', scores: { RT: 3, AM: 3, PE: 3, ID: 2 } },
      { id: 'D', text: '常に挑戦し続けている（10回以上）', scores: { RT: 5, AM: 5, PE: 4, ID: 3 } },
    ],
    measureTypes: ['RT', 'AM', 'PE', 'ID'],
  },
  {
    id: 27,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: '「2年以上継続して取り組んでいること」はいくつありますか？',
    options: [
      { id: 'A', text: '特にない', scores: { PE: 0, SP: 1 } },
      { id: 'B', text: '1つある', scores: { PE: 3, AM: 2 } },
      { id: 'C', text: '2〜3つある', scores: { PE: 4, AM: 3, SP: 2 } },
      { id: 'D', text: '4つ以上ある', scores: { PE: 5, AM: 4, AT: 2 } },
    ],
    measureTypes: ['PE', 'AM'],
  },
  {
    id: 28,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: '副業・フリーランス・起業・投資のいずれかの実践経験はありますか？',
    options: [
      { id: 'A', text: 'まったくない', scores: { SP: 2 } },
      { id: 'B', text: '考えたことはあるが、実行はしていない', scores: { AM: 1, ID: 1 } },
      { id: 'C', text: '小さな規模で試したことがある', scores: { RT: 2, AM: 3, ID: 2, PE: 2 } },
      { id: 'D', text: '現在進行中、または複数回経験あり', scores: { RT: 4, AM: 5, ID: 4, PE: 3, LP: 2 } },
    ],
    measureTypes: ['RT', 'AM', 'ID', 'PE'],
  },
  {
    id: 29,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: 'あなたにとって、仕事やキャリアで最も大切なことは？',
    options: [
      { id: 'A', text: '収入・経済的な自由・資産形成', scores: { AM: 3, RT: 2 } },
      { id: 'B', text: '安定・ワークライフバランス・心の余裕', scores: { SP: 4, PE: 2 } },
      { id: 'C', text: '専門性の深化・スキルや知識の積み上げ', scores: { AT: 3, TA: 3, PE: 3 } },
      { id: 'D', text: '影響力・リーダーシップ・社会への貢献', scores: { LP: 4, SI: 3, AM: 3, ID: 3 } },
    ],
    measureTypes: ['AM', 'SP', 'AT', 'LP', 'PE'],
  },
  {
    id: 30,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: '仲のいい友人・知人5人は、どんな人たちですか？',
    options: [
      { id: 'A', text: '公務員・大企業の社員が多い', scores: { SP: 2 } },
      { id: 'B', text: 'さまざまな職業・業界の人が混在している', scores: { SI: 3, ID: 2, LP: 2 } },
      { id: 'C', text: '起業家・フリーランス・専門職が多い', scores: { RT: 3, AM: 3, ID: 3, LP: 2 } },
      { id: 'D', text: '経営者・高収入・投資家が多い', scores: { RT: 4, AM: 4, LP: 3, AT: 2 } },
    ],
    measureTypes: ['SI', 'RT', 'AM', 'LP'],
  },

  // ─── Section F: 適性・得意分野 ────────────────────────────────────
  {
    id: 31,
    section: 'F',
    sectionLabel: '適性・得意分野',
    question: '学校の授業や勉強で、最も得意・好きだったのはどの分野ですか？',
    options: [
      { id: 'A', text: '数学・物理・情報技術など理系・論理系の科目', scores: { TA: 3, AT: 2 } },
      { id: 'B', text: '国語・英語・文学など言語・表現系の科目', scores: { CT: 3, PE: 1 } },
      { id: 'C', text: '美術・音楽・デザインなど感性・創作系の科目', scores: { CT: 4, ID: 3 } },
      { id: 'D', text: '社会・歴史・倫理など人文・社会系の科目', scores: { SI: 2, LP: 1, AT: 1 } },
    ],
    measureTypes: ['TA', 'CT', 'SI', 'ID'],
  },
  {
    id: 32,
    section: 'F',
    sectionLabel: '適性・得意分野',
    question: '給与が同じだとしたら、どんな仕事が一番楽しそうですか？',
    options: [
      { id: 'A', text: '専門技術・医療・エンジニアリングなど、技術で問題を解く仕事', scores: { TA: 4, AT: 1 } },
      { id: 'B', text: '芸術・デザイン・ライティングなど、表現・創作の仕事', scores: { CT: 4, ID: 3 } },
      { id: 'C', text: 'カウンセリング・教育・福祉など、人を直接サポートする仕事', scores: { SI: 4, PE: 2 } },
      { id: 'D', text: '経営・投資・コンサルなど、戦略・意思決定に関わる仕事', scores: { AM: 3, LP: 2, AT: 1 } },
    ],
    measureTypes: ['TA', 'CT', 'SI', 'AM'],
  },
  {
    id: 33,
    section: 'F',
    sectionLabel: '適性・得意分野',
    question: '周りの人から「自然にそうなってる」「向いてる」とよく言われることに最も近いのは？',
    options: [
      { id: 'A', text: '「技術的なことは任せた」「細かくて正確」「専門的すぎてついていけない」', scores: { TA: 4, PE: 3 } },
      { id: 'B', text: '「話すと楽になる」「人の気持ちをわかってる」「気遣いがすごい」', scores: { SI: 5, PE: 2 } },
      { id: 'C', text: '「発想がユニーク」「センスがいい」「面白いアイデアを出す」', scores: { CT: 4, ID: 3 } },
      { id: 'D', text: '「論理的でわかりやすい」「計画・数字に強い」「判断が的確」', scores: { AT: 2, LP: 2, AM: 2 } },
    ],
    measureTypes: ['TA', 'SI', 'CT', 'AT'],
  },
  {
    id: 34,
    section: 'F',
    sectionLabel: '適性・得意分野',
    question: '仕事の「理想の成果・手応え」として最もイメージに近いのはどれですか？',
    options: [
      { id: 'A', text: '自分が作ったシステム・製品・技術が、実際に動いて使われている', scores: { TA: 4, AT: 2 } },
      { id: 'B', text: '「あなたのおかげで助かった・良くなった」という言葉を直接もらうこと', scores: { SI: 5, PE: 2 } },
      { id: 'C', text: '自分の作品・デザイン・コンテンツが広まり、多くの人の目に触れること', scores: { CT: 4, ID: 3 } },
      { id: 'D', text: '自分が関わったプロジェクト・事業が大きな数字・成果を出したこと', scores: { AM: 4, LP: 2, AT: 1 } },
    ],
    measureTypes: ['TA', 'SI', 'CT', 'AM'],
  },
  {
    id: 35,
    section: 'F',
    sectionLabel: '適性・得意分野',
    question: '今後のキャリアで「絶対に向いていない・したくない仕事」に最も近いのはどれですか？',
    options: [
      { id: 'A', text: '高度な技術・専門知識が求められる細かい専門職・技術職', scores: { TA: -3 } },
      { id: 'B', text: '人の深い悩みや感情に長時間向き合い続ける対人支援の仕事', scores: { SI: -3, SP: 1 } },
      { id: 'C', text: '感性やオリジナリティで評価されるクリエイティブ・表現系の仕事', scores: { CT: -3, SP: 1 } },
      { id: 'D', text: '毎日同じ業務を繰り返す安定・定型型の仕事', scores: { SP: -3, ID: 2, RT: 1 } },
    ],
    measureTypes: ['TA', 'SI', 'CT', 'SP'],
  },
]

export const TOTAL_QUESTIONS = QUESTIONS.length

export const SECTIONS = [
  { id: 'A', label: '日常の選択シナリオ', range: [1, 6] },
  { id: 'B', label: 'お金と時間の選択', range: [7, 12] },
  { id: 'C', label: 'あなたの考え方', range: [13, 18] },
  { id: 'D', label: '性格特性', range: [19, 24] },
  { id: 'E', label: '行動履歴・キャリア志向', range: [25, 30] },
  { id: 'F', label: '適性・得意分野', range: [31, 35] },
]
