import type { Question } from '@/types/diagnosis'

export const QUESTIONS: Question[] = [
  // ─── Section A: 経営判断シナリオ ───────────────────────────────────
  {
    id: 1,
    section: 'A',
    sectionLabel: '経営判断シナリオ',
    question: 'あなたのスタートアップで開発費が予算の80%を消化しましたが、製品は未完成です。投資家への次回報告まで3ヶ月しかありません。どう対応しますか？',
    scenario: '状況: スタートアップ経営者として資金危機に直面',
    options: [
      { id: 'A', text: '投資家に現状を正直に話し、追加調達を交渉する', scores: { RT: 3, LP: 3, AM: 2, AT: 1 } },
      { id: 'B', text: '機能を削減してMVPを早期リリースし、収益化を急ぐ', scores: { ID: 3, AM: 3, AT: 2, RT: 1 } },
      { id: 'C', text: 'コストを大幅削減し、今ある資金を延命する', scores: { SP: 2, AT: 2, PE: 2, LP: 1 } },
      { id: 'D', text: '事業会社への売却・M&Aを積極的に検討する', scores: { AT: 3, RT: -1, AM: 2 } },
    ],
    measureTypes: ['RT', 'LP', 'AM', 'AT', 'ID'],
  },
  {
    id: 2,
    section: 'A',
    sectionLabel: '経営判断シナリオ',
    question: 'あなたのサービスに大手企業が類似製品で参入してきました。価格は50%安く設定されています。どう対応しますか？',
    scenario: '状況: 市場競合が激化する場面での意思決定',
    options: [
      { id: 'A', text: '価格競争には応じず、プレミアムポジションを固める', scores: { AT: 3, ID: 2, AM: 2 } },
      { id: 'B', text: '顧客の声を徹底収集し、差別化機能を急いで開発する', scores: { ID: 3, AT: 2, SI: 2, AM: 2 } },
      { id: 'C', text: '大手に逆提案してパートナーシップを結ぶ', scores: { LP: 2, SI: 3, AM: 2, AT: 1 } },
      { id: 'D', text: 'ニッチ市場に絞り込み、コアユーザーに特化する', scores: { AT: 3, ID: 2, SP: 1 } },
    ],
    measureTypes: ['AT', 'ID', 'SI', 'LP'],
  },
  {
    id: 3,
    section: 'A',
    sectionLabel: '経営判断シナリオ',
    question: '3年間取り組んだ事業が収益化の目途が立ちません。チームも疲弊しています。どうしますか？',
    scenario: '状況: 長期投資に対する撤退判断',
    options: [
      { id: 'A', text: 'もう1年だけ続ける。まだ諦めたくない', scores: { PE: 2, AM: 2, RT: 2 } },
      { id: 'B', text: 'データを徹底分析し、3ヶ月以内に判断基準を設定する', scores: { AT: 4, LP: 2, AM: 2 } },
      { id: 'C', text: 'チームに率直に話し、撤退を決断する', scores: { LP: 3, AT: 2, SP: 1 } },
      { id: 'D', text: '全く別の領域へのピボットを検討する', scores: { ID: 3, RT: 2, AM: 3 } },
    ],
    measureTypes: ['AT', 'LP', 'PE', 'ID', 'RT'],
  },
  {
    id: 4,
    section: 'A',
    sectionLabel: '経営判断シナリオ',
    question: '新サービスの価格設定をしています。コストは月1万円、競合は月3,000〜5,000円です。どの戦略を取りますか？',
    scenario: '状況: 新規サービスの価格戦略決定',
    options: [
      { id: 'A', text: '月9,800円にして価値の高さを訴求する', scores: { RT: 2, ID: 2, AM: 3, AT: 1 } },
      { id: 'B', text: '月4,800円で市場平均に合わせる', scores: { SP: 2, AT: 2 } },
      { id: 'C', text: '月1,980円で圧倒的な安さで市場シェアを取る', scores: { RT: 2, AM: 2, LP: 1 } },
      { id: 'D', text: 'フリーミアムにしてまず利用者数を最大化する', scores: { ID: 3, RT: 2, AM: 2, AT: 2 } },
    ],
    measureTypes: ['RT', 'ID', 'AM', 'AT'],
  },
  {
    id: 5,
    section: 'A',
    sectionLabel: '経営判断シナリオ',
    question: '重要ポジションの採用で迷っています。候補者Aは能力が非常に高いが協調性に難あり。候補者Bは能力は平均的だがチームへの貢献度が高い。',
    scenario: '状況: 採用判断における能力 vs 協調性のトレードオフ',
    options: [
      { id: 'A', text: 'Aを採用する。能力が最優先', scores: { AT: 2, AM: 3, RT: 2 } },
      { id: 'B', text: 'Bを採用する。チームワークが生産性を決める', scores: { SI: 3, LP: 2, SP: 1 } },
      { id: 'C', text: 'どちらも見送り、両方の資質を持つ人材を探す', scores: { LP: 3, PE: 2, AT: 2 } },
      { id: 'D', text: 'Aを採用し、協調性向上のコーチングをセットで実施する', scores: { LP: 4, ID: 2, AT: 2 } },
    ],
    measureTypes: ['LP', 'AT', 'SI', 'AM'],
  },
  {
    id: 6,
    section: 'A',
    sectionLabel: '経営判断シナリオ',
    question: 'メイン事業が成熟期に入り成長が鈍化しています。新規事業に注力するか、現事業を深掘りするか。',
    scenario: '状況: 事業ポートフォリオの転換判断',
    options: [
      { id: 'A', text: 'リソースの7割を新規事業に投入する', scores: { ID: 4, RT: 3, AM: 3 } },
      { id: 'B', text: '現事業を最適化しながら1割のリソースで新規事業を実験する', scores: { AT: 3, PE: 3, AM: 2 } },
      { id: 'C', text: 'M&Aで成長企業を買収し取り込む', scores: { AT: 3, RT: 2, LP: 2 } },
      { id: 'D', text: '現事業のグローバル展開に注力する', scores: { LP: 3, AM: 3, AT: 2, RT: 2 } },
    ],
    measureTypes: ['ID', 'RT', 'AM', 'AT', 'LP'],
  },

  // ─── Section B: 行動経済学的意思決定 ──────────────────────────────
  {
    id: 7,
    section: 'B',
    sectionLabel: '行動経済学的意思決定',
    question: '以下の選択肢のうち、あなたはどれを選びますか？',
    options: [
      { id: 'A', text: '確実に30万円もらえる', scores: { SP: 3, RT: -2 } },
      { id: 'B', text: '50%の確率で70万円、50%の確率で0円', scores: { RT: 3, AM: 2 } },
      { id: 'C', text: '確実に25万円 + 25%の確率で追加20万円', scores: { AT: 3, SP: 1 } },
      { id: 'D', text: '20%の確率で150万円、80%の確率で0円', scores: { RT: 5, AM: 3, ID: 2 } },
    ],
    measureTypes: ['RT', 'SP', 'AM', 'AT'],
  },
  {
    id: 8,
    section: 'B',
    sectionLabel: '行動経済学的意思決定',
    question: '以下の金銭的選択肢のうち、あなたはどれを選びますか？',
    scenario: '時間の価値と将来利益の判断',
    options: [
      { id: 'A', text: '今すぐ10万円', scores: { SP: 3, RT: 1 } },
      { id: 'B', text: '1ヶ月後に12万円', scores: { AT: 2, PE: 2 } },
      { id: 'C', text: '6ヶ月後に20万円', scores: { PE: 4, AT: 2, AM: 2 } },
      { id: 'D', text: '3年後に100万円', scores: { PE: 5, AM: 3, AT: 3 } },
    ],
    measureTypes: ['PE', 'AM', 'AT', 'SP'],
  },
  {
    id: 9,
    section: 'B',
    sectionLabel: '行動経済学的意思決定',
    question: '自由に使える1,000万円があったとしたら、どうしますか？',
    options: [
      { id: 'A', text: 'すべて預金・国債など安全資産に保管する', scores: { SP: 5, RT: -3 } },
      { id: 'B', text: '半分を安全資産、半分を株式・投信で運用する', scores: { SP: 2, RT: 2, AT: 2 } },
      { id: 'C', text: '全額を株式・ETFで積極的に運用する', scores: { RT: 3, AM: 3 } },
      { id: 'D', text: '自分のビジネス・スキルアップに全額投資する', scores: { RT: 4, AM: 5, ID: 3, PE: 3 } },
    ],
    measureTypes: ['RT', 'SP', 'AM', 'ID'],
  },
  {
    id: 10,
    section: 'B',
    sectionLabel: '行動経済学的意思決定',
    question: 'コインを10回投げて、すべて「表」が出ました。次の1回で「表」が出る確率はどのくらいだと思いますか？',
    scenario: '確率的思考力・認知バイアス診断',
    options: [
      { id: 'A', text: '非常に高い（コインは表が出やすい状態にある）', scores: { AT: -2 } },
      { id: 'B', text: '50%（コイン投げは独立した試行なので変わらない）', scores: { AT: 5 } },
      { id: 'C', text: '非常に低い（そろそろ裏が出るはずだ）', scores: { AT: -2 } },
      { id: 'D', text: '理論的には50%だが、感覚的には答えにくい', scores: { AT: 2 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 11,
    section: 'B',
    sectionLabel: '行動経済学的意思決定',
    question: '2年前に200万円で購入した業務用機材があります。現在は使用頻度が低く、売却すれば50万円になります。維持費は月3万円。どうしますか？',
    scenario: 'サンクコスト判断テスト',
    options: [
      { id: 'A', text: '200万円分の価値を取り戻すまで使い続ける', scores: { AT: -2, SP: 2 } },
      { id: 'B', text: '今後の純利益を計算し、維持か売却かを合理的に判断する', scores: { AT: 5 } },
      { id: 'C', text: 'とりあえず様子を見て、すぐには決めない', scores: { SP: 1 } },
      { id: 'D', text: '50万円の損失確定が心理的に嫌なので売却しない', scores: { RT: -1, AT: -1 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 12,
    section: 'B',
    sectionLabel: '行動経済学的意思決定',
    question: '「日本の平均年収は約500万円」という情報を見た直後、あなたの5年後の目標年収は？',
    scenario: 'アンカリング耐性・達成動機測定',
    options: [
      { id: 'A', text: '400〜600万円', scores: { SP: 2, AM: 1 } },
      { id: 'B', text: '600〜900万円', scores: { AM: 2, AT: 1 } },
      { id: 'C', text: '900〜1,500万円', scores: { AM: 3, RT: 2, ID: 2 } },
      { id: 'D', text: '1,500万円以上', scores: { AM: 5, RT: 3, LP: 2 } },
    ],
    measureTypes: ['AM', 'RT', 'LP'],
  },

  // ─── Section C: 認知能力推定 ──────────────────────────────────────
  {
    id: 13,
    section: 'C',
    sectionLabel: '認知能力推定',
    question: '「すべての成功者は努力している。田中さんは努力している。では田中さんは成功者か？」',
    scenario: '論理的思考力テスト',
    options: [
      { id: 'A', text: 'はい、成功者だ', scores: { AT: -2 } },
      { id: 'B', text: 'いいえ、成功者ではない', scores: { AT: -1 } },
      { id: 'C', text: '「成功者は努力する」は「努力すれば成功」を意味しないため、判断できない', scores: { AT: 5 } },
      { id: 'D', text: '努力しているので成功する可能性が高い', scores: { AT: 1 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 14,
    section: 'C',
    sectionLabel: '認知能力推定',
    question: '「木の年輪」を抽象化した概念として、最も深く適切なものを選んでください。',
    scenario: '抽象思考・概念化能力テスト',
    options: [
      { id: 'A', text: '木の模様・見た目的特徴', scores: { AT: 0 } },
      { id: 'B', text: '時間の経過を物理的に記録する構造', scores: { AT: 3, CT: 3 } },
      { id: 'C', text: '自然界における情報の蓄積と可視化システム', scores: { AT: 4, CT: 4, ID: 2 } },
      { id: 'D', text: 'フラクタル構造における成長の痕跡パターン', scores: { AT: 5, CT: 5, ID: 3 } },
    ],
    measureTypes: ['AT', 'CT', 'ID'],
  },
  {
    id: 15,
    section: 'C',
    sectionLabel: '認知能力推定',
    question: '「会社の売上が前年比20%減少している」という問題への、最初のアプローチとして最も優れているのは？',
    scenario: '構造化能力・MECEアプローチテスト',
    options: [
      { id: 'A', text: '営業チームに渇を入れ、訪問件数を増やす', scores: { AM: 1 } },
      { id: 'B', text: '原因を特定するためにまずデータを集める', scores: { AT: 2 } },
      { id: 'C', text: '売上＝顧客数×購買頻度×単価 に分解し、各指標の変化を分析する', scores: { AT: 5 } },
      { id: 'D', text: '競合他社の状況を調査する', scores: { AT: 1 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 16,
    section: 'C',
    sectionLabel: '認知能力推定',
    question: '1から100までの整数をすべて足した合計を求めてください。',
    scenario: '数的推論・問題分解能力テスト',
    options: [
      { id: 'A', text: 'わからない / 計算できない', scores: { AT: 0 } },
      { id: 'B', text: '約4,000〜4,500程度（概算）', scores: { AT: 1 } },
      { id: 'C', text: '5,050（公式を使って算出）', scores: { AT: 4 } },
      { id: 'D', text: '5,050（ガウスの方法: 101×50 として即答）', scores: { AT: 5 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 17,
    section: 'C',
    sectionLabel: '認知能力推定',
    question: '「2, 3, 5, 7, 11, ___」次の数字は何ですか？',
    scenario: 'パターン認識テスト',
    options: [
      { id: 'A', text: '12', scores: { AT: 0 } },
      { id: 'B', text: '13（素数の列と認識して即答）', scores: { AT: 5 } },
      { id: 'C', text: '14', scores: { AT: 0 } },
      { id: 'D', text: 'わからない', scores: { AT: 0 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 18,
    section: 'C',
    sectionLabel: '認知能力推定',
    question: 'ある商品が20%値上がりし、その後20%値下がりしました。最終価格は元の価格と比べてどうなりますか？',
    scenario: '数的推論テスト（複合割合計算）',
    options: [
      { id: 'A', text: '変わらない（+20%と−20%で相殺される）', scores: { AT: -1 } },
      { id: 'B', text: '4%安くなる（1.2×0.8=0.96）', scores: { AT: 5 } },
      { id: 'C', text: '4%高くなる', scores: { AT: -1 } },
      { id: 'D', text: '計算が複雑でわからない', scores: { AT: 0 } },
    ],
    measureTypes: ['AT'],
  },

  // ─── Section D: Big5 性格特性 ─────────────────────────────────────
  {
    id: 19,
    section: 'D',
    sectionLabel: '性格特性 Big5',
    question: '新しい経験・知識・挑戦に対して、最もあなたに当てはまるのは？',
    scenario: '開放性（Openness）測定',
    options: [
      { id: 'A', text: '新しい経験や知識を常に求め、未知の領域に飛び込むことが好き', scores: { ID: 3, CT: 3, RT: 2, AM: 2 } },
      { id: 'B', text: '慣れ親しんだ方法を好み、確実な道を選ぶ傾向がある', scores: { SP: 3, PE: 2 } },
      { id: 'C', text: '面白そうなものには挑戦するが、リスクは慎重に評価する', scores: { AT: 2, RT: 1, AM: 1 } },
      { id: 'D', text: '新しいアイデアを考えるのは好きだが、実行は慎重', scores: { CT: 3, ID: 2 } },
    ],
    measureTypes: ['ID', 'CT', 'SP', 'RT'],
  },
  {
    id: 20,
    section: 'D',
    sectionLabel: '性格特性 Big5',
    question: '締め切りや計画管理について、最もあなたに当てはまるのは？',
    scenario: '誠実性（Conscientiousness）測定',
    options: [
      { id: 'A', text: '綿密な計画を立て、着実に実行する。締め切りは必ず守る', scores: { PE: 4, SP: 2, AM: 2 } },
      { id: 'B', text: '大まかな方向性を決め、状況に応じて柔軟に対応する', scores: { AT: 2, ID: 2, AM: 2 } },
      { id: 'C', text: '直感的に動くことが多く、細かい計画は苦手', scores: { ID: 2, CT: 2 } },
      { id: 'D', text: '重要なことは守るが、細部にはこだわらない', scores: { AM: 2, LP: 1 } },
    ],
    measureTypes: ['PE', 'SP', 'ID', 'AM'],
  },
  {
    id: 21,
    section: 'D',
    sectionLabel: '性格特性 Big5',
    question: 'エネルギーを最も回復できる方法は？',
    scenario: '外向性（Extraversion）測定',
    options: [
      { id: 'A', text: '多くの人と交わり、話すことでエネルギーが高まる', scores: { SI: 4, LP: 2 } },
      { id: 'B', text: '一人の静かな時間で深く考えることでリフレッシュできる', scores: { AT: 3, CT: 2 } },
      { id: 'C', text: '少人数での深い対話が最もエネルギーになる', scores: { SI: 2, AT: 2 } },
      { id: 'D', text: 'チームで協働するのが好きだが、最終判断は自分でしたい', scores: { LP: 3, SI: 2, AM: 2 } },
    ],
    measureTypes: ['SI', 'LP', 'AT', 'CT'],
  },
  {
    id: 22,
    section: 'D',
    sectionLabel: '性格特性 Big5',
    question: 'チーム内で意見が対立したとき、あなたはどうしますか？',
    scenario: '協調性（Agreeableness）測定',
    options: [
      { id: 'A', text: '自分の意見をしっかり主張し、納得いくまで議論する', scores: { LP: 3, AM: 2 } },
      { id: 'B', text: '相手の立場を理解し、妥協点を積極的に探る', scores: { SI: 4, LP: 2 } },
      { id: 'C', text: '大局的に最善を判断し、チームを方向づけるよう努める', scores: { LP: 4, AT: 3, SI: 2 } },
      { id: 'D', text: '対立は避け、周囲の意見に合わせることが多い', scores: { SP: 2, SI: 2 } },
    ],
    measureTypes: ['LP', 'SI', 'AT'],
  },
  {
    id: 23,
    section: 'D',
    sectionLabel: '性格特性 Big5',
    question: '高プレッシャーな状況でのあなたは？',
    scenario: '情緒安定性（Neuroticism逆転）測定',
    options: [
      { id: 'A', text: 'プレッシャーで実力以上を発揮できる興奮状態になる', scores: { AM: 3, LP: 2, RT: 2 } },
      { id: 'B', text: '多少緊張するが、通常通りのパフォーマンスが出る', scores: { PE: 3, SP: 2 } },
      { id: 'C', text: 'プレッシャーで集中力が増し、冷静かつ精密に対処できる', scores: { AT: 3, LP: 2, PE: 2 } },
      { id: 'D', text: '強いプレッシャーではパフォーマンスが低下しやすい', scores: { SP: 3 } },
    ],
    measureTypes: ['AM', 'LP', 'AT', 'PE'],
  },
  {
    id: 24,
    section: 'D',
    sectionLabel: '性格特性 Big5',
    question: '10年後の自分として、最もイメージに近い姿は？',
    scenario: 'キャリアビジョン・総合特性測定',
    options: [
      { id: 'A', text: '自分の会社・プロジェクトをリードし、大きな組織を動かしている', scores: { LP: 4, AM: 4, RT: 3, ID: 3 } },
      { id: 'B', text: 'ある専門分野で業界から認められるエキスパートになっている', scores: { PE: 4, AT: 3, TA: 3, AM: 3 } },
      { id: 'C', text: '安定した収入と充実したプライベートを両立して働いている', scores: { SP: 4, PE: 3 } },
      { id: 'D', text: '自分の仕事を通じて社会や業界に大きな変革をもたらしている', scores: { LP: 3, SI: 3, AM: 3, CT: 3 } },
    ],
    measureTypes: ['LP', 'AM', 'PE', 'SP', 'ID'],
  },

  // ─── Section E: 行動履歴・キャリア志向 ────────────────────────────
  {
    id: 25,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: '読書・講座受講・スキルアップに費やす時間は週平均でどのくらいですか？',
    options: [
      { id: 'A', text: 'ほぼゼロ（1時間未満）', scores: { PE: 0, AM: 0 } },
      { id: 'B', text: '1〜3時間程度', scores: { PE: 1, AM: 1 } },
      { id: 'C', text: '3〜10時間程度', scores: { PE: 3, AM: 3, AT: 2 } },
      { id: 'D', text: '10時間以上', scores: { PE: 5, AM: 5, AT: 3, ID: 2 } },
    ],
    measureTypes: ['PE', 'AM', 'AT'],
  },
  {
    id: 26,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: '過去3年間で「やや怖い・難しい」と感じた挑戦をどれくらいしましたか？',
    options: [
      { id: 'A', text: 'ほぼしていない（1〜2回以下）', scores: { SP: 3, PE: 1 } },
      { id: 'B', text: '数回（3〜5回）', scores: { RT: 2, AM: 2, PE: 2 } },
      { id: 'C', text: '定期的に（6〜10回）', scores: { RT: 3, AM: 3, PE: 3, ID: 2 } },
      { id: 'D', text: '常に挑戦し続けている（10回以上）', scores: { RT: 5, AM: 5, PE: 4, ID: 3 } },
    ],
    measureTypes: ['RT', 'AM', 'PE', 'ID'],
  },
  {
    id: 27,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: '「2年以上継続して取り組んでいること」はいくつありますか？',
    options: [
      { id: 'A', text: '特にない', scores: { PE: 0, SP: 1 } },
      { id: 'B', text: '1つある', scores: { PE: 3, AM: 2 } },
      { id: 'C', text: '2〜3つある', scores: { PE: 4, AM: 3, SP: 2 } },
      { id: 'D', text: '4つ以上ある', scores: { PE: 5, AM: 4, AT: 2 } },
    ],
    measureTypes: ['PE', 'AM'],
  },
  {
    id: 28,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: '副業・フリーランス・起業・投資のいずれかの実践経験は？',
    options: [
      { id: 'A', text: 'まったくない', scores: { SP: 2 } },
      { id: 'B', text: '考えたことはあるが実行していない', scores: { AM: 1, ID: 1 } },
      { id: 'C', text: '小規模に試したことがある', scores: { RT: 2, AM: 3, ID: 2, PE: 2 } },
      { id: 'D', text: '現在進行中、または複数回経験あり', scores: { RT: 4, AM: 5, ID: 4, PE: 3, LP: 2 } },
    ],
    measureTypes: ['RT', 'AM', 'ID', 'PE'],
  },
  {
    id: 29,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: 'あなたにとって、キャリアで最も重要なことは？',
    options: [
      { id: 'A', text: '収入・経済的自由・資産形成', scores: { AM: 3, RT: 2 } },
      { id: 'B', text: '安定・ワークライフバランス・心の余裕', scores: { SP: 4, PE: 2 } },
      { id: 'C', text: '専門性の深化・スキル・知識の蓄積', scores: { AT: 3, TA: 3, PE: 3 } },
      { id: 'D', text: '影響力・リーダーシップ・社会変革', scores: { LP: 4, SI: 3, AM: 3, ID: 3 } },
    ],
    measureTypes: ['AM', 'SP', 'AT', 'LP', 'PE'],
  },
  {
    id: 30,
    section: 'E',
    sectionLabel: '行動履歴・キャリア志向',
    question: 'あなたの周囲（親しい5人）は、どんな人たちですか？',
    scenario: '人的ネットワークと環境要因の測定',
    options: [
      { id: 'A', text: '公務員・大企業会社員が中心', scores: { SP: 2 } },
      { id: 'B', text: 'さまざまな職業・業界の人が混在している', scores: { SI: 3, ID: 2, LP: 2 } },
      { id: 'C', text: '起業家・フリーランス・専門職が多い', scores: { RT: 3, AM: 3, ID: 3, LP: 2 } },
      { id: 'D', text: '経営者・高収入者・投資家が多い', scores: { RT: 4, AM: 4, LP: 3, AT: 2 } },
    ],
    measureTypes: ['SI', 'RT', 'AM', 'LP'],
  },
]

export const TOTAL_QUESTIONS = QUESTIONS.length

export const SECTIONS = [
  { id: 'A', label: '経営判断シナリオ', range: [1, 6] },
  { id: 'B', label: '行動経済学的意思決定', range: [7, 12] },
  { id: 'C', label: '認知能力推定', range: [13, 18] },
  { id: 'D', label: '性格特性 Big5', range: [19, 24] },
  { id: 'E', label: '行動履歴・キャリア志向', range: [25, 30] },
]
