import type { Question } from '@/types/diagnosis'

export const QUESTIONS: Question[] = [
  // ─── Section A: 思考パターン ──────────────────────────────────────────
  {
    id: 1,
    section: 'A',
    sectionLabel: '思考パターン',
    question: '転職のオファーが届きました。給与は30%アップですが、相手は設立2年のスタートアップです。どうしますか？',
    options: [
      { id: 'A', text: '不安はあるが、成長できるチャンスとして前向きに検討する', scores: { RT: 3, LP: 3, AM: 2, AT: 1 } },
      { id: 'B', text: 'まず副業として関わり、会社の実態を確認してから判断する', scores: { ID: 3, AM: 3, AT: 2, RT: 1 } },
      { id: 'C', text: 'リスクが高すぎる。現職の安定を優先する', scores: { SP: 2, AT: 2, PE: 2, LP: 1 } },
      { id: 'D', text: 'このオファーを材料に、現職で昇給交渉を試みる', scores: { AT: 3, RT: -1, AM: 2 } },
    ],
    measureTypes: ['RT', 'LP', 'AM', 'AT', 'ID'],
  },
  {
    id: 5,
    section: 'A',
    sectionLabel: '思考パターン',
    question: 'グループ作業でリーダーを任されました。メンバーAはとても優秀だが自分勝手、メンバーBは実力は普通だがチームを盛り上げてくれます。どちらを重要な役割に配置しますか？',
    options: [
      { id: 'A', text: 'Aに任せる。実力が最優先だ', scores: { AT: 2, AM: 3, RT: 2 } },
      { id: 'B', text: 'Bに任せる。チームの雰囲気が成果を決める', scores: { SI: 3, LP: 2, SP: 1 } },
      { id: 'C', text: '役割をしっかり分けて、AとBどちらの強みも活かす', scores: { LP: 3, PE: 2, AT: 2 } },
      { id: 'D', text: 'AにはBがフォローに入る体制を作り、両方うまく機能させる', scores: { LP: 4, ID: 2, AT: 2 } },
    ],
    measureTypes: ['LP', 'AT', 'SI', 'AM'],
  },
  {
    id: 7,
    section: 'A',
    sectionLabel: '思考パターン',
    question: '次の選択肢から、あなたが選ぶとしたらどれですか？',
    options: [
      { id: 'A', text: '確実に30万円もらえる', scores: { SP: 3, RT: -2 } },
      { id: 'B', text: '50%の確率で70万円、50%の確率で0円', scores: { RT: 3, AM: 2 } },
      { id: 'C', text: '確実に25万円 ＋ 25%の確率で追加20万円', scores: { AT: 3, SP: 1 } },
      { id: 'D', text: '20%の確率で150万円、80%の確率で0円', scores: { RT: 5, AM: 3, ID: 2 } },
    ],
    measureTypes: ['RT', 'SP', 'AM', 'AT'],
  },
  {
    id: 8,
    section: 'A',
    sectionLabel: '思考パターン',
    question: '次の選択肢なら、どれを選びますか？',
    options: [
      { id: 'A', text: '今すぐ10万円', scores: { SP: 3, RT: 1 } },
      { id: 'B', text: '1ヶ月後に12万円', scores: { AT: 2, PE: 2 } },
      { id: 'C', text: '6ヶ月後に20万円', scores: { PE: 4, AT: 2, AM: 2 } },
      { id: 'D', text: '3年後に100万円', scores: { PE: 5, AM: 3, AT: 3 } },
    ],
    measureTypes: ['PE', 'AM', 'AT', 'SP'],
  },
  {
    id: 14,
    section: 'A',
    sectionLabel: '思考パターン',
    question: '「時計」という物を一言で言い換えるとしたら、最もしっくりくるのは？',
    options: [
      { id: 'A', text: '時間を知るための道具', scores: { AT: 0 } },
      { id: 'B', text: '人間が時間を管理・共有するために生まれたシステム', scores: { AT: 3, CT: 3 } },
      { id: 'C', text: '目に見えない時間を物理的に可視化したもの', scores: { AT: 4, CT: 4, ID: 2 } },
      { id: 'D', text: '有限な人間の命を刻み、意識させる装置', scores: { AT: 5, CT: 5, ID: 3 } },
    ],
    measureTypes: ['AT', 'CT', 'ID'],
  },
  {
    id: 18,
    section: 'A',
    sectionLabel: '思考パターン',
    question: '気に入った服が「20%OFF」セールで買えました。翌週さらに「20%OFF」になっていました。合計で元の価格の何%引きになっていますか？',
    options: [
      { id: 'A', text: '40%引き（20%＋20%で計算）', scores: { AT: -1 } },
      { id: 'B', text: '36%引き（0.8×0.8＝0.64、つまり64%の価格）', scores: { AT: 5 } },
      { id: 'C', text: '38%引き', scores: { AT: -1 } },
      { id: 'D', text: 'ちょっと複雑でわからない', scores: { AT: 0 } },
    ],
    measureTypes: ['AT'],
  },
  {
    id: 19,
    section: 'A',
    sectionLabel: '思考パターン',
    question: '新しい経験・知識・挑戦に対して、最もあなたに当てはまるのは？',
    options: [
      { id: 'A', text: '新しい経験や知識を常に求め、未知の領域に飛び込むことが好き', scores: { ID: 3, CT: 3, RT: 2, AM: 2 } },
      { id: 'B', text: '慣れ親しんだ方法を好み、確実な道を選ぶ傾向がある', scores: { SP: 3, PE: 2 } },
      { id: 'C', text: '面白そうなものには挑戦するが、リスクは慎重に評価する', scores: { AT: 2, RT: 1, AM: 1 } },
      { id: 'D', text: '新しいアイデアを考えるのは好きだが、実行は慎重', scores: { CT: 3, ID: 2 } },
    ],
    measureTypes: ['ID', 'CT', 'SP', 'RT'],
  },

  // ─── Section B: 性格・行動 ──────────────────────────────────────────
  {
    id: 21,
    section: 'B',
    sectionLabel: '性格・行動',
    question: 'エネルギーを最も回復できる方法は？',
    options: [
      { id: 'A', text: '多くの人と話したり交流することでエネルギーが高まる', scores: { SI: 4, LP: 2 } },
      { id: 'B', text: '一人で静かに考えたり、好きなことをする時間でリフレッシュできる', scores: { AT: 3, CT: 2 } },
      { id: 'C', text: '少人数での深い会話が一番エネルギーになる', scores: { SI: 2, AT: 2 } },
      { id: 'D', text: 'チームで何かを作ったり達成することが活力になる', scores: { LP: 3, SI: 2, AM: 2 } },
    ],
    measureTypes: ['SI', 'LP', 'AT', 'CT'],
  },
  {
    id: 22,
    section: 'B',
    sectionLabel: '性格・行動',
    question: 'グループや職場で意見が対立したとき、あなたはどうしますか？',
    options: [
      { id: 'A', text: '自分の意見をしっかり主張し、納得いくまで議論する', scores: { LP: 3, AM: 2 } },
      { id: 'B', text: '相手の立場を理解し、妥協点を積極的に探る', scores: { SI: 4, LP: 2 } },
      { id: 'C', text: '全体にとって最善を判断し、チームを方向づけるよう努める', scores: { LP: 4, AT: 3, SI: 2 } },
      { id: 'D', text: '対立は避け、周囲の意見に合わせることが多い', scores: { SP: 2, SI: 2 } },
    ],
    measureTypes: ['LP', 'SI', 'AT'],
  },
  {
    id: 23,
    section: 'B',
    sectionLabel: '性格・行動',
    question: '締め切りや発表など、プレッシャーがかかる場面でのあなたは？',
    options: [
      { id: 'A', text: 'プレッシャーがあるほど燃えて、実力以上を発揮できる', scores: { AM: 3, LP: 2, RT: 2 } },
      { id: 'B', text: '多少緊張するが、通常通りのパフォーマンスが出る', scores: { PE: 3, SP: 2 } },
      { id: 'C', text: 'プレッシャーで集中力が増し、冷静かつ丁寧に対処できる', scores: { AT: 3, LP: 2, PE: 2 } },
      { id: 'D', text: '強いプレッシャーがかかるとパフォーマンスが落ちやすい', scores: { SP: 3 } },
    ],
    measureTypes: ['AM', 'LP', 'AT', 'PE'],
  },
  {
    id: 24,
    section: 'B',
    sectionLabel: '性格・行動',
    question: '10年後の自分として、最もイメージに近い姿は？',
    options: [
      { id: 'A', text: '自分の会社やプロジェクトをリードし、大きな組織を動かしている', scores: { LP: 4, AM: 4, RT: 3, ID: 3 } },
      { id: 'B', text: 'ある分野で業界から認められる専門家になっている', scores: { PE: 4, AT: 3, TA: 3, AM: 3 } },
      { id: 'C', text: '安定した収入と充実したプライベートを両立して働いている', scores: { SP: 4, PE: 3 } },
      { id: 'D', text: '自分の仕事を通じて社会や業界に大きな変化をもたらしている', scores: { LP: 3, SI: 3, AM: 3, CT: 3 } },
    ],
    measureTypes: ['LP', 'AM', 'PE', 'SP', 'ID'],
  },
  {
    id: 28,
    section: 'B',
    sectionLabel: '性格・行動',
    question: '副業・フリーランス・起業・投資のいずれかの実践経験はありますか？',
    options: [
      { id: 'A', text: 'まったくない', scores: { SP: 2 } },
      { id: 'B', text: '考えたことはあるが、実行はしていない', scores: { AM: 1, ID: 1 } },
      { id: 'C', text: '小さな規模で試したことがある', scores: { RT: 2, AM: 3, ID: 2, PE: 2 } },
      { id: 'D', text: '現在進行中、または複数回経験あり', scores: { RT: 4, AM: 5, ID: 4, PE: 3, LP: 2 } },
    ],
    measureTypes: ['RT', 'AM', 'ID', 'PE'],
  },
  {
    id: 29,
    section: 'B',
    sectionLabel: '性格・行動',
    question: 'あなたにとって、仕事やキャリアで最も大切なことは？',
    options: [
      { id: 'A', text: '収入・経済的な自由・資産形成', scores: { AM: 3, RT: 2 } },
      { id: 'B', text: '安定・ワークライフバランス・心の余裕', scores: { SP: 4, PE: 2 } },
      { id: 'C', text: '専門性の深化・スキルや知識の積み上げ', scores: { AT: 3, TA: 3, PE: 3 } },
      { id: 'D', text: '影響力・リーダーシップ・社会への貢献', scores: { LP: 4, SI: 3, AM: 3, ID: 3 } },
    ],
    measureTypes: ['AM', 'SP', 'AT', 'LP', 'PE'],
  },

  // ─── Section C: 適性・志向 ──────────────────────────────────────────
  {
    id: 32,
    section: 'C',
    sectionLabel: '適性・志向',
    question: '給与が同じだとしたら、どんな仕事が一番楽しそうですか？',
    options: [
      { id: 'A', text: '専門技術・医療・エンジニアリングなど、技術で問題を解く仕事', scores: { TA: 4, AT: 1 } },
      { id: 'B', text: '芸術・デザイン・ライティングなど、表現・創作の仕事', scores: { CT: 4, ID: 3 } },
      { id: 'C', text: 'カウンセリング・教育・福祉など、人を直接サポートする仕事', scores: { SI: 4, PE: 2 } },
      { id: 'D', text: '経営・投資・コンサルなど、戦略・意思決定に関わる仕事', scores: { AM: 3, LP: 2, AT: 1 } },
    ],
    measureTypes: ['TA', 'CT', 'SI', 'AM'],
  },
  {
    id: 33,
    section: 'C',
    sectionLabel: '適性・志向',
    question: '周りの人から「自然にそうなってる」「向いてる」とよく言われることに最も近いのは？',
    options: [
      { id: 'A', text: '「技術的なことは任せた」「細かくて正確」「専門的すぎてついていけない」', scores: { TA: 4, PE: 3 } },
      { id: 'B', text: '「話すと楽になる」「人の気持ちをわかってる」「気遣いがすごい」', scores: { SI: 5, PE: 2 } },
      { id: 'C', text: '「発想がユニーク」「センスがいい」「面白いアイデアを出す」', scores: { CT: 4, ID: 3 } },
      { id: 'D', text: '「論理的でわかりやすい」「計画・数字に強い」「判断が的確」', scores: { AT: 2, LP: 2, AM: 2 } },
    ],
    measureTypes: ['TA', 'SI', 'CT', 'AT'],
  },
  {
    id: 35,
    section: 'C',
    sectionLabel: '適性・志向',
    question: '今後のキャリアで「絶対に向いていない・したくない仕事」に最も近いのはどれですか？',
    options: [
      { id: 'A', text: '高度な技術・専門知識が求められる細かい専門職・技術職', scores: { TA: -3 } },
      { id: 'B', text: '人の深い悩みや感情に長時間向き合い続ける対人支援の仕事', scores: { SI: -3, SP: 1 } },
      { id: 'C', text: '感性やオリジナリティで評価されるクリエイティブ・表現系の仕事', scores: { CT: -3, SP: 1 } },
      { id: 'D', text: '毎日同じ業務を繰り返す安定・定型型の仕事', scores: { SP: -3, ID: 2, RT: 1 } },
    ],
    measureTypes: ['TA', 'SI', 'CT', 'SP'],
  },
  {
    id: 37,
    section: 'C',
    sectionLabel: '適性・志向',
    question: '休日、気づいたら自然にやっていることに最も近いのはどれですか？',
    options: [
      { id: 'A', text: '本・ネット・動画などで気になることを調べたり学んでいる', scores: { AT: 4, ID: 2 } },
      { id: 'B', text: '友達・家族・恋人と一緒に過ごしたり、誰かと話している', scores: { SI: 5, AM: 1 } },
      { id: 'C', text: '絵を描く・文章を書く・コードを書くなど一人で何かを作っている', scores: { CT: 4, TA: 2, PE: 2 } },
      { id: 'D', text: '体を動かす・旅・新しい場所や体験を探している', scores: { RT: 3, PE: 3 } },
    ],
    measureTypes: ['AT', 'SI', 'CT', 'TA', 'RT', 'PE'],
  },
  {
    id: 38,
    section: 'C',
    sectionLabel: '適性・志向',
    question: '今すぐ副業を始めるとしたら、どれが一番「やってみたい」と感じますか？',
    options: [
      { id: 'A', text: 'プログラミング・技術系のフリーランス案件', scores: { TA: 5, AT: 2 } },
      { id: 'B', text: 'コーチング・相談・家庭教師などの人と関わる仕事', scores: { SI: 5, PE: 2 } },
      { id: 'C', text: 'YouTube・ブログ・イラスト・創作などの発信活動', scores: { CT: 5, ID: 2 } },
      { id: 'D', text: '株・FX・不動産など投資・資産運用の勉強・実践', scores: { RT: 4, AM: 3, AT: 2 } },
    ],
    measureTypes: ['TA', 'SI', 'CT', 'RT', 'AM', 'AT'],
  },
  {
    id: 39,
    section: 'C',
    sectionLabel: '適性・志向',
    question: '学生の頃、クラスや学校での自分のポジションに最も近いのはどれですか？',
    options: [
      { id: 'A', text: '黙々と自分の作業・勉強に集中していることが多かった', scores: { TA: 3, PE: 3, SP: 2 } },
      { id: 'B', text: '友達の悩みや相談に乗る「話を聞いてくれる人」だった', scores: { SI: 5, LP: 2 } },
      { id: 'C', text: '新しいことを企画・提案したり、面白いことを考えていた', scores: { ID: 4, AM: 2, RT: 2 } },
      { id: 'D', text: '部活・委員会・グループ活動でリーダーになることが多かった', scores: { LP: 5, AM: 2 } },
    ],
    measureTypes: ['TA', 'PE', 'SI', 'LP', 'ID', 'AM'],
  },
  {
    id: 40,
    section: 'C',
    sectionLabel: '適性・志向',
    question: '仕事をしていて「これが一番やりがいだ」と感じる瞬間はどれに近いですか？',
    options: [
      { id: 'A', text: '複雑な問題をロジカルに分析して解決したとき', scores: { AT: 5, AM: 2 } },
      { id: 'B', text: '誰かに「ありがとう、助かった」と直接言われたとき', scores: { SI: 4, PE: 3 } },
      { id: 'C', text: '自分の作品・成果物が形になり、多くの人の目に触れたとき', scores: { CT: 4, ID: 3, PE: 1 } },
      { id: 'D', text: '目標を大きく超えた数字・成果を叩き出したとき', scores: { AM: 5, RT: 2 } },
    ],
    measureTypes: ['AT', 'AM', 'SI', 'CT', 'ID', 'PE', 'RT'],
  },
]

export const TOTAL_QUESTIONS = QUESTIONS.length

export const SECTIONS = [
  { id: 'A', label: '思考パターン', range: [1, 19] },
  { id: 'B', label: '性格・行動', range: [21, 29] },
  { id: 'C', label: '適性・志向', range: [32, 40] },
]
